apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - fastapi_deploy.yaml
  - fastapi_service.yaml  

images:
  - name: huangyuan2000/fastapi-inference
    newTag: a04294f
namespace: fastapi-inference